GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/669ece0e5191b28daae7cc03

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Nextjs router"
}